import { DriverProfile } from "./components/Profilecard";

export const driverProfiles: DriverProfile[] = [
  {
    id: 1,
    picture: "/avatar.jpg",
    name: "John Doe",
    phone: "+1234567890",
    sex: "Male",
    age: 30,
    carRegistration: "F OFF",
    carModel: "Porsche GT3",
    carPicture: "/PorscheGT3.jpg",
    rating: 4.5,
  },
  {
    id: 2,
    picture: "/avatar.jpg",
    name: "Jane Smith",
    phone: "+1234567891",
    sex: "Female",
    age: 28,
    carRegistration: "X2 COOL",
    carModel: "Porsche GT3",
    carPicture: "/PorscheGT3.jpg",
    rating: 4.7,
  },
  {
    id: 3,
    picture: "/avatar.jpg",
    name: "Mike Johnson",
    phone: "+1234567892",
    sex: "Male",
    age: 35,
    carRegistration: "SPEEDY",
    carModel: "Porsche GT3",
    carPicture: "/PorscheGT3.jpg",
    rating: 4.9,
  },
  {
    id: 4,
    picture: "/avatar.jpg",
    name: "Emily Davis",
    phone: "+1234567893",
    sex: "Female",
    age: 27,
    carRegistration: "DRVR4U",
    carModel: "Porsche GT3",
    carPicture: "/PorscheGT3.jpg",
    rating: 4.8,
  },
  {
    id: 5,
    picture: "/avatar.jpg",
    name: "David Brown",
    phone: "+1234567894",
    sex: "Male",
    age: 40,
    carRegistration: "VROOOM",
    carModel: "Porsche GT3",
    carPicture: "/PorscheGT3.jpg",
    rating: 4.6,
  },
  {
    id: 6,
    picture: "/avatar.jpg",
    name: "Olivia Wilson",
    phone: "+1234567895",
    sex: "Female",
    age: 32,
    carRegistration: "NXTGEN",
    carModel: "Porsche GT3",
    carPicture: "/PorscheGT3.jpg",
    rating: 4.4,
  },
  {
    id: 7,
    picture: "/avatar.jpg",
    name: "Chris Lee",
    phone: "+1234567896",
    sex: "Male",
    age: 29,
    carRegistration: "FAST4U",
    carModel: "Porsche GT3",
    carPicture: "/PorscheGT3.jpg",
    rating: 4.3,
  },
  {
    id: 8,
    picture: "/avatar.jpg",
    name: "Sophia Martinez",
    phone: "+1234567897",
    sex: "Female",
    age: 26,
    carRegistration: "GO2GO",
    carModel: "Porsche GT3",
    carPicture: "/PorscheGT3.jpg",
    rating: 4.2,
  },
  {
    id: 9,
    picture: "/avatar.jpg",
    name: "Brian Anderson",
    phone: "+1234567898",
    sex: "Male",
    age: 33,
    carRegistration: "RACERX",
    carModel: "Porsche GT3",
    carPicture: "/PorscheGT3.jpg",
    rating: 4.1,
  },
  {
    id: 10,
    picture: "/avatar.jpg",
    name: "Linda Thompson",
    phone: "+1234567899",
    sex: "Female",
    age: 31,
    carRegistration: "CARFUN",
    carModel: "Porsche GT3",
    carPicture: "/PorscheGT3.jpg",
    rating: 4.0,
  },
];
